### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by jplukas**

### CODE REVIEW

**Comment by jplukas** [comment]
@all-contributors please add @jplukas for code

**Comment by jplukas** [comment]
@all-contributors
please add @jplukas for docs
please add @lineconquista
please add @lulcca
please add @bachiari
please add @igorney
please add @LeTrovoes
please add @rafaelhs-debug
please add @thenriique

**Comment by jplukas** [comment]
@all-contributors
please add @jplukas for docs
please add @lineconquista for code
please add @lulcca for code
please add @bachiari for code
please add @igorney for code
please add @LeTrovoes for code
please add @rafaelhs-debug for code
please add @thenriique for code
please add @Ingrid27 for code
please add @Will0890 for code

**Comment by lulcca** [comment]
adeus gitmoji 😭

**Comment by jplukas** [comment]
> adeus gitmoji 😭

Hahah desculpa, ainda estou acertando tudo
Fala pra mim suas emoji keys pra eu colocar certinho @lulcca

**Pull request merged**
